import type { Metadata } from 'next'
import { Noto_Serif_Display, Ubuntu } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/components/Navbar'
import { NextFont } from 'next/dist/compiled/@next/font'
import Image from 'next/image'

const ubuntu: NextFont = Ubuntu(
  {
    subsets: ['latin'],
    weight: '400'
  }
)

const noto_bold: NextFont = Noto_Serif_Display({
  subsets: ['latin'],
  weight: '900'
})

const ubuntu_bold: NextFont = Ubuntu(
  {
    subsets: ['latin'],
    weight: '700',
    variable: '--ubuntu-bold'
  }
)

export const metadata: Metadata = {
  title: 'Class Schedule Thaskala X7',
  description: 'Jadwal pelajaran kelas 10-7 citra nusa tahun pelajaran 2023/2024',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='overflow-hidden bg-[#8c52ff]'>
      <body className={ubuntu.className}>
        <header className='bg-[#8c52ff]'>
          <div className='flex justify-center'>
            <h1 className={`${noto_bold.className} animate-bounce z-50 mt-7 drop-shadow-[-1px_2px_27px_rgba(255,255,255,0.6)] text-5xl absolute`}>THASKALA</h1>
          </div>
          <div className={`mx-[-30px] text-[#481666] overflow-hidden ${ubuntu_bold.className} text-center text-nowrap bold-bold text-3xl`}>
            <p>
              CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE
            </p>
            <p>
              CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE
            </p>
            <p>
              CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE CLASS SCHEDULE
            </p>
          </div>
        </header>
        <div className='flex flex-col'>
          <Image className='md:block hidden animate-ping top-[120px] md:top-[170px] ml-[-260px] absolute md:ml-[-10px]' src="/stars.svg" alt='stars' width="350" height="350"/>
          <div className='bg-[#8c52ff] pt-10'>{children}</div>
          <Image className='md:block hidden animate-ping top-[120px] right-0 md:top-[170px] mr-[-260px] absolute md:mr-[-10px]' src="/stars.svg" alt='stars' width="340" height="340"/>
          <Navbar />
        </div>
      </body>
    </html>
  )
}
